version: '3.9'

volumes:
  mongo_data:
services:
  mongodb:
    restart: 'always'
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
