version: '3.5'

volumes:
  mongo_data:

services:
  api01: &api
    image: gabrielroque/rinha-api:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=rinha
    ports:
      - '8081:8080'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '200MB'

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=rinha
    ports:
      - '8082:8080'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '10MB'

  db:
    restart: 'always'
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=rinha
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.45'
    #       memory: '140MB'
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
